# Site settings
title: Thotful
description: The only podcast that makes you think about things you would never have thot to think about... thotfully
keywords: Thotful, Thoughtful, Podcast, Comedy, Squirrels
author: Unnas Hussain and Kellie Laflin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "thotfulpodcast.github.io" # the base hostname & protocol for your site
